# Generated by Django 6.0.6 on 2026-09-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expenserecord_supplier"),
        ("inventory", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="dti_registration",
            field=models.CharField(
                blank=True,
                help_text="Optional DTI registration no.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("net15", "Net 15"),
                    ("net30", "Net 30"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_suppliers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_suppliers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SupplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("made_to_order", "Made to Order"),
                            ("seasonal", "Seasonal"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_items",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_items",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Item",
                "verbose_name_plural": "Supply Items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expected_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("announced", "Announced"),
                            ("received", "Received"),
                            ("rejected", "Rejected"),
                        ],
                        default="announced",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_notice",
                        to="expenses.expenserecord",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_notices",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "supply_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_notices",
                        to="suppliers.supplyitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Notice",
                "verbose_name_plural": "Delivery Notices",
                "ordering": ["-expected_date"],
            },
        ),
    ]
