# Generated by Django 6.0.6 on 2026-09-23 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_approve_existing_suppliers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynotice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_delivery_notices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverynotice",
            name="origin",
            field=models.CharField(
                choices=[("supplier", "Supplier Announced"), ("farm", "Farm Ordered")],
                default="supplier",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="deliverynotice",
            name="supplier_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
