# Generated by Django 6.0.6 on 2026-09-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0004_deliverynotice_created_by_deliverynotice_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynotice",
            name="status",
            field=models.CharField(
                choices=[
                    ("announced", "Announced"),
                    ("confirmed", "Confirmed"),
                    ("received", "Received"),
                    ("rejected", "Rejected"),
                ],
                default="announced",
                max_length=20,
            ),
        ),
    ]
