# Generated by Django 6.0.6 on 2026-09-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_sales_product_type"),
        ("suppliers", "0005_alter_deliverynotice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplyitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Farm stock row this item adds to when a delivery is received (set by staff).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supply_items",
                to="inventory.inventoryitem",
            ),
        ),
    ]
