# Generated by Django 6.0.6 on 2026-09-25 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_sales_product_type"),
        ("suppliers", "0006_supplyitem_inventory_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynotice",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Stock row this delivery was booked into (decided at receive; overrides the catalog default).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notices",
                to="inventory.inventoryitem",
            ),
        ),
    ]
