# Generated by Django 6.0.6 on 2026-09-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0007_deliverynotice_inventory_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverynotice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Delivery Notice",
                "verbose_name_plural": "Delivery Notices",
            },
        ),
    ]
