# Generated by Django 6.0.6 on 2026-09-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyers", "0003_approve_existing_buyers"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrequest",
            name="source",
            field=models.CharField(
                choices=[("portal", "Buyer Portal"), ("staff", "On Behalf (Staff)")],
                default="portal",
                max_length=10,
            ),
        ),
    ]
