# Generated by Django 6.0.6 on 2026-06-24 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("farm_size", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "farm_type",
                    models.CharField(
                        choices=[
                            ("layer", "Layer Farm"),
                            ("broiler", "Broiler Farm"),
                            ("mixed", "Mixed Farm"),
                        ],
                        default="mixed",
                        max_length=50,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="farm_logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Profile",
                "verbose_name_plural": "Farm Profiles",
            },
        ),
    ]
