# Generated by Django 6.0.6 on 2026-09-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("owner", "Farm Owner"),
                    ("staff", "Staff/Caretaker"),
                    ("buyer", "Buyer"),
                    ("supplier", "Supplier"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
