# Generated by Django 6.0.6 on 2026-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="sales_product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eggs", "Eggs"),
                    ("chicken", "Live Chicken"),
                    ("dressed", "Dressed Chicken"),
                    ("manure", "Manure"),
                    ("other", "Other"),
                ],
                help_text="Optional: recorded sales of this product type deduct from this item's stock.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
