# Generated by Django 6.0.6 on 2026-06-24 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flocks", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[
                            ("medicine", "Medicine"),
                            ("vaccine", "Vaccine"),
                            ("vitamin", "Vitamin"),
                        ],
                        default="medicine",
                        max_length=20,
                    ),
                ),
                ("medicine_name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "quantity_used",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("date_administered", models.DateField()),
                (
                    "administration_route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("injection", "Injection"),
                            ("spray", "Spray"),
                            ("water", "In Water"),
                            ("other", "Other"),
                        ],
                        default="oral",
                        max_length=50,
                    ),
                ),
                ("next_schedule", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_records",
                        to="flocks.flockbatch",
                    ),
                ),
                (
                    "medicine_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicine_records",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Record",
                "verbose_name_plural": "Medicine Records",
                "ordering": ["-date_administered"],
            },
        ),
    ]
