# Generated by Django 6.0.6 on 2026-06-24 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("breed", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "current_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("age_days", models.PositiveIntegerField(default=0)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("date_acquired", models.DateField()),
                (
                    "growing_stage",
                    models.CharField(
                        choices=[
                            ("chick", "Chick"),
                            ("grower", "Grower"),
                            ("layer", "Layer"),
                            ("broiler", "Broiler"),
                        ],
                        default="chick",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("depleted", "Depleted"),
                            ("culled", "Culled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flock Batch",
                "verbose_name_plural": "Flock Batches",
                "ordering": ["-date_acquired"],
            },
        ),
    ]
