# Generated by Django 6.0.6 on 2026-09-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Low Stock Alert"),
                    ("expired", "Expired Item Alert"),
                    ("vaccination", "Vaccination Reminder"),
                    ("mortality", "High Mortality Warning"),
                    ("activity", "Activity Notification"),
                    ("order_request", "Order Request"),
                    ("delivery_notice", "Delivery Notice"),
                    ("account", "Account Review"),
                ],
                max_length=20,
            ),
        ),
    ]
